version: 1
disable_existing_loggers: false

formatters:
  simple:
    format: "%(asctime)s %(levelname)s %(name)s: %(message)s"

handlers:
  app_console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  app_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: logs/app.log
    maxBytes: 10485760
    backupCount: 5

loggers:
  app:
    handlers: [app_console, app_file]
    level: DEBUG
    propagate: false

root:
  handlers: [app_console]
  level: WARNING
